fix: remove bigint type from response of getTransaction api
Transak/eGLD-elrond-mainet pull request #5
Opened 2021-11-24 14:17 UTC by Minhaj-ul-abidin

as  bigint is not bson serialisable

2021-11-24 14:37 UTC, thakursachin467 commented
@Minhaj-ul-abidin can you format the response of `getTransaction ` similar to how we do it with celo https://github.com/Transak/celo-transak/blob/main/index.js#L103

2021-11-24 15:02 UTC, agarwalyeshu requested changes

2021-11-24 15:02 UTC, agarwalyeshu commented on index.js
> +getTransaction("d6a4e99a0c23f6931765121592ef7746107ee49920374ffe836ee04efeba7ec3","main").then(console.log)
We should receive this right ?

2021-11-24 16:36 UTC, Minhaj-ul-abidin commented on index.js
> +getTransaction("d6a4e99a0c23f6931765121592ef7746107ee49920374ffe836ee04efeba7ec3","main").then(console.log)
Right fixing this.

2021-11-25 19:37 UTC, Minhaj-ul-abidin commented
Changes already pushed in #6

2021-11-25 19:37 UTC, closed without merging